### ISSUE TITLE
RewriteRule hilighting breaks when tabs are used

### ISSUE THREAD

**Issue by draeath** [jacobbednarz/atom-language-apache#15]
Tabs used between fields in a RewriteRule are not handled by the highlighter as whitespace. See attached image for example (they may be difficult to see, but invisibles are printed as a lighter grey)

Yes, the whitespacing in this file is atrocious - but you do run into junk like this in production sadly.

![color-issue](https://cloud.githubusercontent.com/assets/987449/22251929/7ffd43e6-e21a-11e6-9a96-d6ac73944db5.png)

**Comment by jacobbednarz** [comment]
@draeath I gave this a run in #16. Can you please that branch locally and try it against the file you're having issues with?
