### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by hilyin** [jacobbednarz/atom-language-apache#5]
Hi I am having trouble installing this package, what is the proper way to install it?

Thank you!

**Comment by jacobbednarz** [comment]
hey @hilyin,
this package is available via atom packages so it should be a matter of opening up the preferences, clicking on 'packages' and typing in apache (the atom [docs](https://atom.io/docs/latest/customizing-atom) also offer other ways of installing if that doesn't work).

if you have any errors or more information, drop it in here and I will check it out.

**Comment by hilyin** [comment]
Thanks man! I must have been in the packages tab rather than install tab and didn't see it. Apologies! It is working great now.
