### ISSUE TITLE
Feature request: support for single quotes

### ISSUE THREAD

**Issue by valtlait** [jacobbednarz/atom-language-apache#8]
Strings marked up with double quotes are highlighted correctly but single quoted ones aren’t:

<img width="468" alt="foo2" src="https://cloud.githubusercontent.com/assets/5496284/11981558/6e01c8c6-a9ac-11e5-99f0-37e784eb1af4.png">

It would be very nice if both was supported.

**Comment by jacobbednarz** [comment]
This seems like a reasonable request! Would you be able to provide a pull request for the changes?

**Comment by valtlait** [comment]
Yes, here it is: #9

**Comment by valtlait** [comment]
Done (PR #9). Closing.
